# pandas의 고유한 자료구조 - Series와 DataFrame
pandas에서는 고유하게 정의한 자료 구조인 Series와 DataFrame을 사용하여 빅데이터 분석을 할 수 있다.

# 1) Series

In [2]:
import pandas as pd
import numpy as np

In [3]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3])

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj.dtype

dtype('int64')

In [7]:
obj.shape

(4,)

In [11]:
obj2=pd.Series([4,7,-5,3], index=['d','b','c','a'])
obj2

d    4
b    7
c   -5
a    3
dtype: int64

# 2) DataFrame
- DataFrame은 pd.DataFrame() 함수를 사용하여 정의한다. (엑셀처럼) DataFrame에 입력할 데이터는 Python 딕셔너리 혹은 numpy의 2차원 array 등의 형태가 될 수 있다.

In [14]:
data = {
    "names": ['Hyerim','Hyerim','Hyerim','Charles','Charles'],
    "year": [2014,2015,2016,2015,2016],
    "points": [1.5, 1.7, 3.6, 2.4, 2.9]
}
df = pd.DataFrame(data)
df

     names  year  points
0   Hyerim  2014     1.5
1   Hyerim  2015     1.7
2   Hyerim  2016     3.6
3  Charles  2015     2.4
4  Charles  2016     2.9

In [15]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [16]:
df.columns

Index(['names', 'year', 'points'], dtype='object')

In [17]:
df.values

array([['Hyerim', 2014, 1.5],
       ['Hyerim', 2015, 1.7],
       ['Hyerim', 2016, 3.6],
       ['Charles', 2015, 2.4],
       ['Charles', 2016, 2.9]], dtype=object)

In [ ]:
# describe 함수
각 컬럼 평균, 분산, 최소/최대값 등 기본 통계량을 산출한 결과를 보여준다.

In [18]:
df.describe() # 숫자 있는 컬럼값들 에 각종 통계값 기본적으로 보여준다!!

             year    points
count     5.00000  5.000000
mean   2015.20000  2.420000
std       0.83666  0.864292
min    2014.00000  1.500000
25%    2015.00000  1.700000
50%    2015.00000  2.400000
75%    2016.00000  2.900000
max    2016.00000  3.600000

In [20]:
df2 = pd.DataFrame(data, columns = ['year','names','points','penalty'], index = ['1','2','3','4','5'])
df2

   year    names  points penalty
1  2014   Hyerim     1.5     NaN
2  2015   Hyerim     1.7     NaN
3  2016   Hyerim     3.6     NaN
4  2015  Charles     2.4     NaN
5  2016  Charles     2.9     NaN

In [21]:
df2.index

Index(['1', '2', '3', '4', '5'], dtype='object')

In [22]:
df2.columns

Index(['year', 'names', 'points', 'penalty'], dtype='object')

In [23]:
df2.values

array([[2014, 'Hyerim', 1.5, nan],
       [2015, 'Hyerim', 1.7, nan],
       [2016, 'Hyerim', 3.6, nan],
       [2015, 'Charles', 2.4, nan],
       [2016, 'Charles', 2.9, nan]], dtype=object)

# DataFrame 을 활용한 분석