In [1]:
# DataFrame 인덱싱

In [2]:
import pandas as pd
import numpy as np

In [7]:
# 데이터 프레임을 하나 만들어 둔다.
data = {
    "names": ['aaa','aaa','bbb','ccc','ccc'],
    "year": [2014,2015,2016,2015,2016],
    "points": [1.5, 1.7, 3.6, 2.4, 2.9]
}
df = pd.DataFrame(data, columns=['year', 'names','points','penalty'], index=['one','two','three','four','five'])
df

       year names  points penalty
one    2014   aaa     1.5     NaN
two    2015   aaa     1.7     NaN
three  2016   bbb     3.6     NaN
four   2015   ccc     2.4     NaN
five   2016   ccc     2.9     NaN

In [9]:
# year 열에 대한 값만 가져오기
df.year

one      2014
two      2015
three    2016
four     2015
five     2016
Name: year, dtype: int64

In [ ]:
# 두 개 이상의 열을 가져올 때는 이중 배열 형태

In [10]:
df[['year', 'points']]

       year  points
one    2014     1.5
two    2015     1.7
three  2016     3.6
four   2015     2.4
five   2016     2.9

In [12]:
# 값 넣기
df.penalty = 0.5
df

       year names  points  penalty
one    2014   aaa     1.5      0.5
two    2015   aaa     1.7      0.5
three  2016   bbb     3.6      0.5
four   2015   ccc     2.4      0.5
five   2016   ccc     2.9      0.5

In [14]:
ㄴ# 행마다 다른 값 넣기
df.penalty = [0.1, 0.2, 0.3, 0.4, 0.5]
df

       year names  points  penalty
one    2014   aaa     1.5      0.1
two    2015   aaa     1.7      0.2
three  2016   bbb     3.6      0.3
four   2015   ccc     2.4      0.4
five   2016   ccc     2.9      0.5

In [17]:
# 컬럼 하나 더 추가하고 값 넣어보기 이건 .으로 접근하면 안되고 [''] 로 해야됨.
df['zeors'] = np.arange(5)
df

       year names  points  penalty  zeors
one    2014   aaa     1.5      0.1      0
two    2015   aaa     1.7      0.2      1
three  2016   bbb     3.6      0.3      2
four   2015   ccc     2.4      0.4      3
five   2016   ccc     2.9      0.5      4

In [19]:
# 시리즈 데이터 만들기
val = pd.Series([-1.2, -1.5, -1.7], index=['two','four','five'])
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [20]:
df['debt'] = val
df

       year names  points  penalty  zeors  debt
one    2014   aaa     1.5      0.1      0   NaN
two    2015   aaa     1.7      0.2      1  -1.2
three  2016   bbb     3.6      0.3      2   NaN
four   2015   ccc     2.4      0.4      3  -1.5
five   2016   ccc     2.9      0.5      4  -1.7

In [21]:
# 연산을 통해 연산 결과를 새로운 컬럼에 넣기
df['net_points'] = df.points - df.penalty
df

       year names  points  penalty  zeors  debt  net_points
one    2014   aaa     1.5      0.1      0   NaN         1.4
two    2015   aaa     1.7      0.2      1  -1.2         1.5
three  2016   bbb     3.6      0.3      2   NaN         3.3
four   2015   ccc     2.4      0.4      3  -1.5         2.0
five   2016   ccc     2.9      0.5      4  -1.7         2.4

In [22]:
df['high_points'] = df.net_points>2.0
df

       year names  points  penalty  zeors  debt  net_points  high_points
one    2014   aaa     1.5      0.1      0   NaN         1.4        False
two    2015   aaa     1.7      0.2      1  -1.2         1.5        False
three  2016   bbb     3.6      0.3      2   NaN         3.3         True
four   2015   ccc     2.4      0.4      3  -1.5         2.0        False
five   2016   ccc     2.9      0.5      4  -1.7         2.4         True

In [30]:
# 기존의 열 삭제하기
#del df['high_points']
#del df['net_points']
#del df['zeros']
df

       year names  points  penalty  zeors  debt
one    2014   aaa     1.5      0.1      0   NaN
two    2015   aaa     1.7      0.2      1  -1.2
three  2016   bbb     3.6      0.3      2   NaN
four   2015   ccc     2.4      0.4      3  -1.5
five   2016   ccc     2.9      0.5      4  -1.7

In [32]:
# 이름 변경하기
df.index.name = 'Order'
df.columns.name = 'Info'
df

Info   year names  points  penalty  zeors  debt
Order
one    2014   aaa     1.5      0.1      0   NaN
two    2015   aaa     1.7      0.2      1  -1.2
three  2016   bbb     3.6      0.3      2   NaN
four   2015   ccc     2.4      0.4      3  -1.5
five   2016   ccc     2.9      0.5      4  -1.7

In [ ]:
# 행 제어하기

In [33]:
df[0:3]

Info   year names  points  penalty  zeors  debt
Order
one    2014   aaa     1.5      0.1      0   NaN
two    2015   aaa     1.7      0.2      1  -1.2
three  2016   bbb     3.6      0.3      2   NaN

In [34]:
# 문자로 범위 인덱싱도 가능하다.
df['two':'four']

Info   year names  points  penalty  zeors  debt
Order
two    2015   aaa     1.7      0.2      1  -1.2
three  2016   bbb     3.6      0.3      2   NaN
four   2015   ccc     2.4      0.4      3  -1.5

# 행 선택하는 권장 방법: .loc(), .iloc()
- loc: 컬럼 명 기준 인덱싱
- iloc: 자리수 기준 인덱싱

In [35]:
# 
df.loc['two'] # 인덱스 가 two인 행의 전체 값을 가져온다.

Info
year       2015
names       aaa
points      1.7
penalty     0.2
zeors         1
debt       -1.2
Name: two, dtype: object

In [36]:
df.loc['two':'four'] # 문자를 기준으로 범위 인덱싱

Info   year names  points  penalty  zeors  debt
Order
two    2015   aaa     1.7      0.2      1  -1.2
three  2016   bbb     3.6      0.3      2   NaN
four   2015   ccc     2.4      0.4      3  -1.5

In [38]:
# points 컬럼의 특정 값만 가져오기 - loc 형태 인덱싱
df.loc['two':'four', 'points'] # 행범위인덱싱, 열값은 points

Order
two      1.7
three    3.6
four     2.4
Name: points, dtype: float64

In [39]:
# 전체 행 값 가져오고, 거기에서 year컬럼의 값만 가져오기!!
df.loc[:, 'year']

Order
one      2014
two      2015
three    2016
four     2015
five     2016
Name: year, dtype: int64

In [40]:
df.loc[:, ['year', 'names']] # year와 names 에 대한 전체 값 가져옴.

Info   year names
Order
one    2014   aaa
two    2015   aaa
three  2016   bbb
four   2015   ccc
five   2016   ccc

In [41]:
# 2~3행에 대해 year, names 가져옴.
df.loc['two':'four', ['year','names']]

Info   year names
Order
two    2015   aaa
three  2016   bbb
four   2015   ccc

In [50]:
#df.loc['six',:] = [2017, 'ddd', 3.3, 0.6, -1.3]
#df

In [48]:
# .iloc는 numpy 방식으로 (행/열 자리값으로)

In [49]:
df.iloc[3]

Info
year       2015.0
names         ccc
points        2.4
penalty       0.4
zeors         3.0
debt         -1.5
Name: four, dtype: object

In [52]:
# 0,1,2까지 0~3행값(3개), 0,1까지 0~2열값(2개) 가져온다.
df.iloc[0:3, 0:2]

Info     year names
Order
one    2014.0   aaa
two    2015.0   aaa
three  2016.0   bbb

In [53]:
# 가끔 0,1,3행 이렇게 가져오고 싶을 때, 행과 열의 범위를 별도 지정해서 인덱싱
df.iloc[[0,1,3], [1,2]]

Info  names  points
Order
one     aaa     1.5
two     aaa     1.7
four    ccc     2.4

In [54]:
df.iloc[:,1:4]

Info  names  points  penalty
Order
one     aaa     1.5      0.1
two     aaa     1.7      0.2
three   bbb     3.6      0.3
four    ccc     2.4      0.4
five    ccc     2.9      0.5
six     NaN     NaN      NaN

In [55]:
# 값 하나만 가져오기
df.iloc[1,1] #1행1열

'aaa'

# 불리언 인덱싱

In [56]:
# year의 2014년보다 큰 값 찾기 (연도에서 2014년보다 큰값)
df.year>2014

Order
one      False
two       True
three     True
four      True
five      True
six      False
Name: year, dtype: bool

In [57]:
## add컬럼 만들고 거기에 2014보다 크면 true를 넣음
add = df.year>2014
df['add'] = add
df.loc[:]

Info     year names  points  penalty  zeors  debt    add
Order
one    2014.0   aaa     1.5      0.1    0.0   NaN  False
two    2015.0   aaa     1.7      0.2    1.0  -1.2   True
three  2016.0   bbb     3.6      0.3    2.0   NaN   True
four   2015.0   ccc     2.4      0.4    3.0  -1.5   True
five   2016.0   ccc     2.9      0.5    4.0  -1.7   True
six       NaN   NaN     NaN      NaN    NaN   NaN  False

In [58]:
## 불리언 값에 의해 인덱싱
df.loc[df.year>2014, :] #year가 2014보다 큰거 전체 뽑음

Info     year names  points  penalty  zeors  debt   add
Order
two    2015.0   aaa     1.7      0.2    1.0  -1.2  True
three  2016.0   bbb     3.6      0.3    2.0   NaN  True
four   2015.0   ccc     2.4      0.4    3.0  -1.5  True
five   2016.0   ccc     2.9      0.5    4.0  -1.7  True

In [59]:
## names가 ccc에 해당되는 names와 points정보 뽑아오기
df.loc[df.names=='ccc', ['names', 'points']]

Info  names  points
Order
four    ccc     2.4
five    ccc     2.9

In [60]:
## points 값 2보다 크고 3보다 작은 값 인덱싱
df.loc[(df.points>2) & (df.points<3), :]

Info     year names  points  penalty  zeors  debt   add
Order
four   2015.0   ccc     2.4      0.4    3.0  -1.5  True
five   2016.0   ccc     2.9      0.5    4.0  -1.7  True

In [64]:
## 포인트값이 3보다 큰것은 penalty 값을 0으로 대임
df.loc[df.points>3, 'penalty']=0
df

Info     year names  points  penalty  zeors  debt    add
Order
one    2014.0   aaa     1.5      0.1    0.0   NaN  False
two    2015.0   aaa     1.7      0.2    1.0  -1.2   True
three  2016.0   bbb     3.6      0.0    2.0   NaN   True
four   2015.0   ccc     2.4      0.4    3.0  -1.5   True
five   2016.0   ccc     2.9      0.5    4.0  -1.7   True
six       NaN   NaN     NaN      NaN    NaN   NaN  False