In [1]:
import pandas as pd
import numpy as np

In [2]:
## numpy타입으로 6행 4열 랜덤 데이터 만들고 데이터 프레임으로 변환
df = pd.DataFrame(np.random.randn(6,4))
df

          0         1         2         3
0 -0.607519  0.095231  0.019684  1.312375
1 -0.162704 -1.635482 -1.827414  0.527138
2 -0.290556  0.951769  0.404897 -1.416715
3 -0.371304 -0.455236  0.874623  1.698982
4 -0.982878  1.284845 -0.443540  0.896384
5  1.431373  0.631840  0.655092 -1.414714

In [3]:
## 6일간의 데이터를 인덱스 값으로 만들어서 뽑아본다.
df.columns = ['a','b','c','d']
df.index = pd.date_range('20250501', periods=6)
df.index

DatetimeIndex(['2025-05-01', '2025-05-02', '2025-05-03', '2025-05-04',
               '2025-05-05', '2025-05-06'],
              dtype='datetime64[ns]', freq='D')

In [4]:
df

                   a         b         c         d
2025-05-01 -0.607519  0.095231  0.019684  1.312375
2025-05-02 -0.162704 -1.635482 -1.827414  0.527138
2025-05-03 -0.290556  0.951769  0.404897 -1.416715
2025-05-04 -0.371304 -0.455236  0.874623  1.698982
2025-05-05 -0.982878  1.284845 -0.443540  0.896384
2025-05-06  1.431373  0.631840  0.655092 -1.414714

In [5]:
## f컬럼에 여러가지 값들 추가
df['f']=[1.0, np.nan, 3.5, 6.1, np.nan, 7.0]
df

                   a         b         c         d    f
2025-05-01 -0.607519  0.095231  0.019684  1.312375  1.0
2025-05-02 -0.162704 -1.635482 -1.827414  0.527138  NaN
2025-05-03 -0.290556  0.951769  0.404897 -1.416715  3.5
2025-05-04 -0.371304 -0.455236  0.874623  1.698982  6.1
2025-05-05 -0.982878  1.284845 -0.443540  0.896384  NaN
2025-05-06  1.431373  0.631840  0.655092 -1.414714  7.0

In [6]:
## NAN 값만 제거하기 (how='any'는 nan이 하나라도 포함되어 있으면 그 행을 다 지우는 것이다.)
df.dropna(how='any')

                   a         b         c         d    f
2025-05-01 -0.607519  0.095231  0.019684  1.312375  1.0
2025-05-03 -0.290556  0.951769  0.404897 -1.416715  3.5
2025-05-04 -0.371304 -0.455236  0.874623  1.698982  6.1
2025-05-06  1.431373  0.631840  0.655092 -1.414714  7.0

In [7]:
## nan이 행 전체에 있을 경우 해당 행을 삭제하기
df.dropna(how='all')

                   a         b         c         d    f
2025-05-01 -0.607519  0.095231  0.019684  1.312375  1.0
2025-05-02 -0.162704 -1.635482 -1.827414  0.527138  NaN
2025-05-03 -0.290556  0.951769  0.404897 -1.416715  3.5
2025-05-04 -0.371304 -0.455236  0.874623  1.698982  6.1
2025-05-05 -0.982878  1.284845 -0.443540  0.896384  NaN
2025-05-06  1.431373  0.631840  0.655092 -1.414714  7.0

In [8]:
## nan 값을 대체하기 (5로 대체한다.)
df.fillna(value=5.0)

                   a         b         c         d    f
2025-05-01 -0.607519  0.095231  0.019684  1.312375  1.0
2025-05-02 -0.162704 -1.635482 -1.827414  0.527138  5.0
2025-05-03 -0.290556  0.951769  0.404897 -1.416715  3.5
2025-05-04 -0.371304 -0.455236  0.874623  1.698982  6.1
2025-05-05 -0.982878  1.284845 -0.443540  0.896384  5.0
2025-05-06  1.431373  0.631840  0.655092 -1.414714  7.0

In [9]:
## 혹은 불리언 마스크로 값을 제어한다.
df.isnull() # nan 값이 있는것만 true로 표기된다. (nan 값이 있는지 확인)

                a      b      c      d      f
2025-05-01  False  False  False  False  False
2025-05-02  False  False  False  False   True
2025-05-03  False  False  False  False  False
2025-05-04  False  False  False  False  False
2025-05-05  False  False  False  False   True
2025-05-06  False  False  False  False  False

In [10]:
## f열에서 NAN 값이 있는 모든 행을 가져온다.
df.loc[df.isnull()['f'], :]

                   a         b         c         d   f
2025-05-02 -0.162704 -1.635482 -1.827414  0.527138 NaN
2025-05-05 -0.982878  1.284845 -0.443540  0.896384 NaN

In [11]:
## 인덱스(현재는 날짜로 되어있음) 기준으로 행을 삭제한다.
pd.to_datetime('20250505') #인덱스가 해당날짜인 것을 가져옴

Timestamp('2025-05-05 00:00:00')

In [12]:
## 인덱스가 5월 5일인 행을 삭제한다. (날짜는 데이트타임으로 인덱싱해야한다)
df.drop(pd.to_datetime('20250505'))

                   a         b         c         d    f
2025-05-01 -0.607519  0.095231  0.019684  1.312375  1.0
2025-05-02 -0.162704 -1.635482 -1.827414  0.527138  NaN
2025-05-03 -0.290556  0.951769  0.404897 -1.416715  3.5
2025-05-04 -0.371304 -0.455236  0.874623  1.698982  6.1
2025-05-06  1.431373  0.631840  0.655092 -1.414714  7.0

In [13]:
# 인덱스 기준으로 두개 이상의 행(5/4, 5/6일)을 삭제한다.
df.drop([pd.to_datetime('20250504'), pd.to_datetime('20250506')])

                   a         b         c         d    f
2025-05-01 -0.607519  0.095231  0.019684  1.312375  1.0
2025-05-02 -0.162704 -1.635482 -1.827414  0.527138  NaN
2025-05-03 -0.290556  0.951769  0.404897 -1.416715  3.5
2025-05-05 -0.982878  1.284845 -0.443540  0.896384  NaN

In [14]:
# f열 전체 삭제하기
df.drop('f', axis=1)

                   a         b         c         d
2025-05-01 -0.607519  0.095231  0.019684  1.312375
2025-05-02 -0.162704 -1.635482 -1.827414  0.527138
2025-05-03 -0.290556  0.951769  0.404897 -1.416715
2025-05-04 -0.371304 -0.455236  0.874623  1.698982
2025-05-05 -0.982878  1.284845 -0.443540  0.896384
2025-05-06  1.431373  0.631840  0.655092 -1.414714

In [15]:
## 여러 열 한번에 삭제하기
df.drop(['b', 'd'], axis=1)

                   a         c    f
2025-05-01 -0.607519  0.019684  1.0
2025-05-02 -0.162704 -1.827414  NaN
2025-05-03 -0.290556  0.404897  3.5
2025-05-04 -0.371304  0.874623  6.1
2025-05-05 -0.982878 -0.443540  NaN
2025-05-06  1.431373  0.655092  7.0

In [16]:
## 데이터 만들기
data = [
    [1.40, np.nan],
    [7.10, -4.5],
    [np.nan, np.nan],
    [0.75, -1.3]
]
data

[[1.4, nan], [7.1, -4.5], [nan, nan], [0.75, -1.3]]

In [17]:
## 데이터 프레임으로 변환하기
df = pd.DataFrame(data, columns = ['one','two'], index=['a','b','c','d'])
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [18]:
## [중요] 행방향으로 열의 합을 계산한다 ==> nan값은 배제하고 계산된다.
df.sum(axis=0)

one    9.25
two   -5.80
dtype: float64

In [19]:
## 열방향으로 각 행의 합을 계산
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [20]:
## 특정 열 또는 행의 값 계산 (one 컬럼에 대해 sum)
df.one.sum()

np.float64(9.25)

In [21]:
df.loc['b'].sum()

np.float64(2.5999999999999996)

In [22]:
## two 행에 대해 평균 계산
df.mean(axis=0)['two']

np.float64(-2.9)

In [23]:
## 열에 대해 평균 내는데, nan값이 있으면 그 행은 스킵하고 계산하기
df.mean(axis=1, skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [24]:
## one_mean 변수에 'one' 행의 평균값을 넣는다.
one_mean = df.mean(axis=0)['one'] # one의 평균값
two_min = df.min(axis=0)['two'] # two의 최소값

In [25]:
## na값을 이런 식으로 교체한다.
df.one = df['one'].fillna(value=one_mean)
df.two = df['two'].fillna(value=two_min)
df

        one  two
a  1.400000 -4.5
b  7.100000 -4.5
c  3.083333 -4.5
d  0.750000 -1.3

In [26]:
## 상관계수 구하기 - 데이터 프레임 준비
df2 = pd.DataFrame(
    np.random.randn(6,4), 
    columns=['a','b','c','d'], 
    index=pd.date_range('20250101', periods=6)
)
df2

                   a         b         c         d
2025-01-01  0.327965  1.277903  0.371383  0.994741
2025-01-02  1.456937  0.977404 -0.427571  0.811181
2025-01-03  0.644526 -0.365007 -0.108349  0.651723
2025-01-04  0.875030  0.766875  0.693078  1.780171
2025-01-05 -1.192566  1.843054 -0.644599  1.099324
2025-01-06 -1.157221  1.165088 -0.174111 -0.828891

In [27]:
## [중요] df2 데이터프레임의 a열과 b열의 상관계수 산출하기 (피어슨 상관계수로 계산)
df2.b.corr(df2.c)

np.float64(-0.2661217479182768)

In [28]:
## 전체를 상관관계로 표현
df2.corr()

          a         b         c         d
a  1.000000 -0.536443  0.384250  0.508644
b -0.536443  1.000000 -0.266122 -0.001591
c  0.384250 -0.266122  1.000000  0.388611
d  0.508644 -0.001591  0.388611  1.000000

In [29]:
## 불규칙하게 데이터를 섞는다.
dates = df2.index
random_dates = np.random.permutation(dates)
df2 = df2.reindex(index=random_dates, columns=['a','b','c','d'])
df2

                   a         b         c         d
2025-01-03  0.644526 -0.365007 -0.108349  0.651723
2025-01-01  0.327965  1.277903  0.371383  0.994741
2025-01-06 -1.157221  1.165088 -0.174111 -0.828891
2025-01-04  0.875030  0.766875  0.693078  1.780171
2025-01-02  1.456937  0.977404 -0.427571  0.811181
2025-01-05 -1.192566  1.843054 -0.644599  1.099324

In [30]:
## 인덱스를 오름차순 정렬
df2.sort_index(axis=0)

                   a         b         c         d
2025-01-01  0.327965  1.277903  0.371383  0.994741
2025-01-02  1.456937  0.977404 -0.427571  0.811181
2025-01-03  0.644526 -0.365007 -0.108349  0.651723
2025-01-04  0.875030  0.766875  0.693078  1.780171
2025-01-05 -1.192566  1.843054 -0.644599  1.099324
2025-01-06 -1.157221  1.165088 -0.174111 -0.828891

In [31]:
## 컬럼 기준으로 오름차순 정렬
df2.sort_index(axis=1)

                   a         b         c         d
2025-01-03  0.644526 -0.365007 -0.108349  0.651723
2025-01-01  0.327965  1.277903  0.371383  0.994741
2025-01-06 -1.157221  1.165088 -0.174111 -0.828891
2025-01-04  0.875030  0.766875  0.693078  1.780171
2025-01-02  1.456937  0.977404 -0.427571  0.811181
2025-01-05 -1.192566  1.843054 -0.644599  1.099324

In [32]:
## 컬럼 기준으로 내림차순 정렬 (두번째 인자에 ascending=False 를 주어야 한다.)
df2.sort_index(axis=0, ascending=False)

                   a         b         c         d
2025-01-06 -1.157221  1.165088 -0.174111 -0.828891
2025-01-05 -1.192566  1.843054 -0.644599  1.099324
2025-01-04  0.875030  0.766875  0.693078  1.780171
2025-01-03  0.644526 -0.365007 -0.108349  0.651723
2025-01-02  1.456937  0.977404 -0.427571  0.811181
2025-01-01  0.327965  1.277903  0.371383  0.994741

In [33]:
## value 기준으로 오름차순 정렬
df2.sort_values(by='a')

                   a         b         c         d
2025-01-05 -1.192566  1.843054 -0.644599  1.099324
2025-01-06 -1.157221  1.165088 -0.174111 -0.828891
2025-01-01  0.327965  1.277903  0.371383  0.994741
2025-01-03  0.644526 -0.365007 -0.108349  0.651723
2025-01-04  0.875030  0.766875  0.693078  1.780171
2025-01-02  1.456937  0.977404 -0.427571  0.811181

In [34]:
## b값을 기준으로 내림차순 정렬
df2.sort_values(by='b', ascending=False)

                   a         b         c         d
2025-01-05 -1.192566  1.843054 -0.644599  1.099324
2025-01-01  0.327965  1.277903  0.371383  0.994741
2025-01-06 -1.157221  1.165088 -0.174111 -0.828891
2025-01-02  1.456937  0.977404 -0.427571  0.811181
2025-01-04  0.875030  0.766875  0.693078  1.780171
2025-01-03  0.644526 -0.365007 -0.108349  0.651723

In [35]:
## 랜덤 값 채움
df2['e'] = np.random.randint(0,6,size=6)
df2['f'] = ['alpha','beta','gamma','gamma','alpha','gamma']
df2

                   a         b         c         d  e      f
2025-01-03  0.644526 -0.365007 -0.108349  0.651723  5  alpha
2025-01-01  0.327965  1.277903  0.371383  0.994741  5   beta
2025-01-06 -1.157221  1.165088 -0.174111 -0.828891  3  gamma
2025-01-04  0.875030  0.766875  0.693078  1.780171  4  gamma
2025-01-02  1.456937  0.977404 -0.427571  0.811181  2  alpha
2025-01-05 -1.192566  1.843054 -0.644599  1.099324  5  gamma

In [36]:
## 
df2.f.unique()

array(['alpha', 'beta', 'gamma'], dtype=object)

In [37]:
df2.f.value_counts()

f
gamma    3
alpha    2
beta     1
Name: count, dtype: int64

In [38]:
## f열에 특정 값 있는지 검색 -> true/false
df2.f.isin(['alpha','gamma'])

2025-01-03     True
2025-01-01    False
2025-01-06     True
2025-01-04     True
2025-01-02     True
2025-01-05     True
Name: f, dtype: bool

In [39]:
## f열에서 알파 감마가 있는 행의 모든 값을 뽑는다.
df2.loc[df2.f.isin(['alpha','gamma']), :]

                   a         b         c         d  e      f
2025-01-03  0.644526 -0.365007 -0.108349  0.651723  5  alpha
2025-01-06 -1.157221  1.165088 -0.174111 -0.828891  3  gamma
2025-01-04  0.875030  0.766875  0.693078  1.780171  4  gamma
2025-01-02  1.456937  0.977404 -0.427571  0.811181  2  alpha
2025-01-05 -1.192566  1.843054 -0.644599  1.099324  5  gamma

In [40]:
## 파이썬 람다함수 간단 생성 및 덧셈 연산
add = lambda x, y : x+y
print(add(3,5))

8

In [41]:
## 데이터프레임 하나 생성
df3 = pd.DataFrame(np.random.randn(4,3), index=['Seoul','Incheon','Busan','Daegu'], columns=['b','d','e'])
df3

                b         d         e
Seoul    0.454518 -0.595717 -1.138848
Incheon  0.494773 -1.332890  0.999814
Busan    1.673656 -0.600875 -0.151273
Daegu    0.339070 -1.183617 -0.968526

In [43]:
## 람다함수를 활용하여 연산 진행 (x.max: 행 또는 열의 최대값, x.min: 행 또는 열의 최소값)
func = lambda x: x.max()-x.min()

In [44]:
## 행 방향으로 해당 함수 열 값이 계산된다
df3.apply(func, axis=0) # 행 방향으로 열 별 람다함수 값을 계산한다.

b    1.334586
d    0.737173
e    2.138663
dtype: float64