In [183]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

AttributeError: module 'matplotlib._api' has no attribute 'MatplotlibDeprecationWarning'

In [6]:
## DF로 데이터를 읽어온다.
df = pd.read_csv('./data/loan.csv', sep=',')

C:\Users\human3_02\AppData\Local\Temp\ipykernel_2140\725548175.py:2: DtypeWarning: Columns (19,47,55,112,123,124,125,128,129,130,133,139,140,141) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('./data/loan.csv', sep=',')

In [7]:
## 10개를 확인해 본다
df.head(10)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,2500,2500,2500.0,36 months,13.56,84.92,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,30000,30000,30000.0,60 months,18.94,777.23,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,5000,5000,5000.0,36 months,17.97,180.69,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,4000,4000,4000.0,36 months,18.94,146.51,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,30000,30000,30000.0,60 months,16.14,731.78,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,5550,5550,5550.0,36 months,15.02,192.45,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,2000,2000,2000.0,36 months,17.97,72.28,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,6000,6000,6000.0,36 months,13.56,203.79,C,C1,...,NaN,NaN,DirectPay,N,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,5000,5000,5000.0,36 months,17.97,180.69,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,6000,6000,6000.0,36 months,14.47,206.44,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
## df의 상태 확인(행 몇개인지, 열 몇개인지)
df.shape

(2260668, 145)

In [10]:
## 컬럼 어떤 것 있는지 확인
df.columns

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       ...
       'hardship_payoff_balance_amount', 'hardship_last_payment_amount',
       'disbursement_method', 'debt_settlement_flag',
       'debt_settlement_flag_date', 'settlement_status', 'settlement_date',
       'settlement_amount', 'settlement_percentage', 'settlement_term'],
      dtype='object', length=145)

In [11]:
## 뒤에서 5번째 행까지 데이터 확인
df.tail(5)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
2260663,NaN,NaN,12000,12000,12000.0,60 months,14.08,279.72,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260664,NaN,NaN,12000,12000,12000.0,60 months,25.82,358.01,E,E4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260665,NaN,NaN,10000,10000,10000.0,36 months,11.99,332.10,B,B5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260666,NaN,NaN,12000,12000,12000.0,60 months,21.45,327.69,D,D5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2260667,NaN,NaN,16550,16550,16550.0,60 months,21.45,451.94,D,D5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
## 필요한 컬럼만 가져오기
df2 = df[['loan_amnt','loan_status','grade','int_rate','term']]

In [13]:
df2.head(5)

   loan_amnt loan_status grade  int_rate        term
0       2500     Current     C     13.56   36 months
1      30000     Current     D     18.94   60 months
2       5000     Current     D     17.97   36 months
3       4000     Current     D     18.94   36 months
4      30000     Current     C     16.14   60 months

In [14]:
## 데이터 중복값 없는지 확인해보기
df2['loan_status'].unique()

array(['Current', 'Fully Paid', 'Late (31-120 days)', 'In Grace Period',
       'Charged Off', 'Late (16-30 days)', 'Default',
       'Does not meet the credit policy. Status:Fully Paid',
       'Does not meet the credit policy. Status:Charged Off'],
      dtype=object)

In [15]:
## grade엔 어떤 값들 있는지 확인
df2['grade'].unique()

array(['C', 'D', 'B', 'A', 'E', 'F', 'G'], dtype=object)

In [16]:
## term엔 어떤 값들 있는지 확인
df2['term'].unique()

array([' 36 months', ' 60 months'], dtype=object)

In [17]:
df2.shape

(2260668, 5)

In [18]:
## pandas df - nan 제거하기(dropna). how를 any로 두면 nan이 있는 그 행은 모두 삭제된다!!! / 반면 how를 all로 두면 그 행 전체가 nan인 경우에만 삭제된다.
df2 = df2.dropna(how='any')
df2.shape # 제거 전과 같다. nan 값이 없다는 것이다.

(2260668, 5)

In [ ]:
## df2 데이터를 가지고 세부 분석 할 예정 (어제 실습 내용 토대로)

# pandas df 문제. 30개월/60개월 두 가지 대출 상품을 운영
-  loan_amnt, loan_status, grade, int_rate, term 이걸 기반으로 인사이트 도출

## 문제1) '36개월 대출'과 '60개월 대출'의 대출 총액 계산

# 문제 1번 교수님 풀이

In [149]:
## 결과를 저장할 딕셔너리 생성
term_to_loan_amnt_dict = {}
## term 컬럼의 고유값 추출
uniq_terms = df2.term.unique()

In [150]:
## 각 대출기간(term)에 대해 반복 계산을 수행 -> 해당 행들의 loan_amnt(대출금액) 컬럼의 합계를 계산한다.
for term in uniq_terms:
    # df2.loc[df2.term] 값이 uniq_term의 term과 같으면, loan_amnt의 열을 갖고 와서 sum을 수행한다.
    loan_amnt_sum = df2.loc[df2.term==term, 'loan_amnt'].sum()
    # 계산된 합계를 딕셔너리에 저장한다.
    term_to_loan_amnt_dict[term] = loan_amnt_sum

In [151]:
term_to_loan_amnt_dict

{'36 months': np.int64(34016115925)}

In [152]:
import matplotlib.pyplot as plt

plt.figure(figsize(8,5))
plt.bar(
    term_to_loan_amnt_dict.keys(),
    term_to_loan_amnt_dict.values(),
)

plt.title('Total Loan Amount by Term') # 그래프 타이틀
plt.xlabel('Loan Term') # x축 레이블
plt.ylabel('Total Loan Amount') # y축 레이블

plt.show()

AttributeError: module 'matplotlib._api' has no attribute 'MatplotlibDeprecationWarning'

In [22]:
## df2에서 36개월 대출인 행과 60개월 대출인 행을 모두 가져와서 다 더한다.
df2.term=='36 months'

0          True
1          True
2          True
3          True
4          True
           ...
2260663    True
2260664    True
2260665    True
2260666    True
2260667    True
Name: term, Length: 2260668, dtype: bool

In [30]:
## 값 확인
df['term'].unique()

array([' 36 months', ' 60 months'], dtype=object)

In [130]:
## 36이랑 60인거 loan amnt 가져오기 => .sum() 으로 더하기
one_answer_df = df.loc[(df.term==' 36 months')|(df.term==' 60 months'), ['loan_amnt']].sum(axis=0)
one_answer_df

loan_amnt    34016115925
dtype: int64

## 문제2) '각 대출 상태(불량/우량)에 따른 대출 등급 분포 파악
- 불량과 우량의 기준점?? 'Current', 'Fully Paid',, 'In Grace Period',
       'Does not meet the credit policy. Status:Fully Paid',
       
- 불량(bad_status_arr): ['Charged Off', 'Default', 'Does not meet the credit policy. Status:Charged Off', 'Late (16-30 days)', 'Late (31-120 days)']
- 우량: 나머지

# 교수님 풀이

In [153]:
df2.loan_status.unique()

array(['Current', 'Fully Paid', 'Late (31-120 days)', 'In Grace Period',
       'Charged Off', 'Late (16-30 days)', 'Default',
       'Does not meet the credit policy. Status:Fully Paid',
       'Does not meet the credit policy. Status:Charged Off'],
      dtype=object)

In [158]:
## loan_status 고유값 추출 및 저장
total_status_category = df2['loan_status'].unique()

## 불량 등급만 모으기 (인덱스로 정의)
bad_status_category = total_status_category[[1,3,4,5,6,8]] # 불량 등급들 정의
bad_status_category # 이런 상태이면 불량인 것이다.

array(['Fully Paid', 'In Grace Period', 'Charged Off',
       'Late (16-30 days)', 'Default',
       'Does not meet the credit policy. Status:Charged Off'],
      dtype=object)

In [164]:
## 컬럼을 추가해 loan_status가 bad_status에 속하면 true, 아니면 false 표시 => 그럼 이제 풀량과 우량의 등급이 구분됐다.
df2['bad_loan_status'] = df2.loan_status.isin(bad_status_category)
df2.head(2)

   loan_amnt loan_status grade  int_rate       term  bad_loan_status
0       2500     Current     C     13.56  36 months            False
1      30000     Current     D     18.94  36 months            False

In [166]:
## bad_loan_status의 값이 true인 행의 grade 값에 대한 분포 확인
## --> 불량 대출 행만 선택해서, 해당 grade의 빈도수(count)를 계산
bad_loan_status_to_grades = df2.loc[df2.bad_loan_status==True, 'grade'].value_counts()  ## true인 것의 grade 값을 가져옴 + 카운트 계산
bad_loan_status_to_grades

grade
B    383075
C    374606
A    227188
D    198279
E     92861
F     31922
G      9157
Name: count, dtype: int64

In [169]:
## 불량상태 보기좋게 등급수 정렬
bad_loan_status_to_grades.sort_index(ascending=True)

grade
A    227188
B    383075
C    374606
D    198279
E     92861
F     31922
G      9157
Name: count, dtype: int64

In [172]:
## 우량등급 분포 확인
good_loan_status_to_grades = df2.loc[df2.bad_loan_status==False, 'grade'].value_counts()
good_loan_status_to_grades

grade
B    280482
C    275447
A    205839
D    126145
E     42778
F      9878
G      3011
Name: count, dtype: int64

In [173]:
## 등급순 정렬
good_loan_status_to_grades.sort_index(ascending=True)

grade
A    205839
B    280482
C    275447
D    126145
E     42778
F      9878
G      3011
Name: count, dtype: int64

In [175]:
## 가볍게 시각화 - 불량 대출 등급 분포
plt.figure(figsize=(8,5))
bad_loan_status_to_grades.sort_index().plot(
    kind='bar'
)

plt.title('Bad Loan Grade Distribution') # 그래프 타이틀
plt.xlabel('Grade') # x축 레이블
plt.ylabel('Count') # y축 레이블

plt.show()

NameError: name 'plt' is not defined

In [177]:
## 한번에 같이 표현
good_grade_counts = good_loan_status_to_grades.sort_index()
bad_grade_counts = bad_loan_status_to_grades.sort_index()

## 두 개 series를 하나의 데이터 프레임으로 결합 - pd concat
compare_df = pd.concat(
    [good_grade_counts, bad_grade_counts],
    axis=1
)

In [178]:
## 컬럼명 지정
compare_df.columns = ['Good Loan','Bad Loan']
## 결측값이 있으면 0으로 대체
compare_df = compare_df.fillna(0) 

## 시각화
compare_df.plot(
    kind = 'bar',
    figsize = (10,6)
)

plt.title('Good Loan vs Bad Loan by Grade') # 그래프 타이틀
plt.xlabel('Grade') # x축 레이블
plt.ylabel('Count') # y축 레이블
plt.xticks(rotation=0)

plt.show()

AttributeError: module 'matplotlib._api' has no attribute 'MatplotlibDeprecationWarning'

In [182]:
## 비율로 표현
grade_status = pd.crosstab(
    df2.grade,
    df2.bad_loan_status,
    normalize = 'index'
)
grade_status

bad_loan_status     False     True
grade
A                0.475349  0.524651
B                0.422695  0.577305
C                0.423730  0.576270
D                0.388828  0.611172
E                0.315381  0.684619
F                0.236316  0.763684
G                0.247452  0.752548

In [ ]:
grade_status.plot(
    kind='bar',
    stacked=True,
    figsize = (10,6)
)

plt.title('Good Loan vs Bad Loan by Grade') # 그래프 타이틀
plt.xlabel('Grade') # x축 레이블
plt.ylabel('Count') # y축 레이블
plt.xticks(rotation=0)

plt.show()

# 나의 풀이

In [36]:
df2.head(5)

   loan_amnt loan_status grade  int_rate       term
0       2500     Current     C     13.56  36 months
1      30000     Current     D     18.94  36 months
2       5000     Current     D     17.97  36 months
3       4000     Current     D     18.94  36 months
4      30000     Current     C     16.14  36 months

In [37]:
## 대출 상태: loan_status 필드값들 확인...
df2.loan_status.unique()

array(['Current', 'Fully Paid', 'Late (31-120 days)', 'In Grace Period',
       'Charged Off', 'Late (16-30 days)', 'Default',
       'Does not meet the credit policy. Status:Fully Paid',
       'Does not meet the credit policy. Status:Charged Off'],
      dtype=object)

In [69]:
## 불량 상태 배열 정의
bad_status_arr = ['Charged Off', 'Default', 'Does not meet the credit policy. Status:Charged Off', 'Late (16-30 days)', 'Late (31-120 days)']
bas_status_index_arr = [1,3,4,5,6,8]

In [60]:
## 불량 고객과 우량 고객 각각에서 등급이 어떻게 분포되어 있는가
## 대출 상태(loan_status)와 대출 등급(grade)의 분포를 파악하면 될 것 같다..

In [105]:
## df2에서 특정컬럼(loan_status)이 불량 고객인 것만 가져오기
badDf2 = df2.loc[(df2.loan_status.isin(bad_status_arr)), :]
badDf2

         loan_amnt         loan_status grade  int_rate       term
1777         20975  Late (31-120 days)     A      8.19  36 months
3203         20000  Late (31-120 days)     B     11.80  36 months
3677          9100  Late (31-120 days)     E     26.31  36 months
4022          3525  Late (31-120 days)     E     25.34  36 months
4768         11500  Late (31-120 days)     C     13.56  36 months
...            ...                 ...   ...       ...        ...
2260638      30000         Charged Off     D     21.45  36 months
2260639      21000  Late (31-120 days)     D     17.09  36 months
2260640      20700         Charged Off     C     12.62  36 months
2260654      30000         Charged Off     D     17.09  36 months
2260655      18000         Charged Off     F     30.65  36 months

[288081 rows x 5 columns]

In [106]:
## df2에서 특정컬럼(loan_status)이 우량 고객인 것만 가져오기
goodDf2 = df2.loc[(df2.loan_status.isin(bad_status_arr)==False), :]
goodDf2

         loan_amnt loan_status grade  int_rate       term
0             2500     Current     C     13.56  36 months
1            30000     Current     D     18.94  36 months
2             5000     Current     D     17.97  36 months
3             4000     Current     D     18.94  36 months
4            30000     Current     C     16.14  36 months
...            ...         ...   ...       ...        ...
2260663      12000     Current     C     14.08  36 months
2260664      12000  Fully Paid     E     25.82  36 months
2260665      10000     Current     B     11.99  36 months
2260666      12000     Current     D     21.45  36 months
2260667      16550     Current     D     21.45  36 months

[1972587 rows x 5 columns]

In [107]:
## 각각 특정 컬럼만 가져오게 다시 변경
badDf2 = badDf2[['loan_status','grade']]
goodDf2 = goodDf2[['loan_status','grade']]

In [100]:
badDf2

        grade
1777        A
3203        B
3677        E
4022        E
4768        C
...       ...
2260638     D
2260639     D
2260640     C
2260654     D
2260655     F

[288081 rows x 1 columns]

In [108]:
goodDf2

        loan_status grade
0           Current     C
1           Current     D
2           Current     D
3           Current     D
4           Current     C
...             ...   ...
2260663     Current     C
2260664  Fully Paid     E
2260665     Current     B
2260666     Current     D
2260667     Current     D

[1972587 rows x 2 columns]

In [118]:
## 이제 각각의 분포? 를 확인해 보면 될 것 같은데 어떻게 하는거지?
badDf2.grade.value_counts()

grade
C    92386
D    65460
B    56750
E    38087
A    15357
F    15190
G     4851
Name: count, dtype: int64

In [111]:
goodDf2.grade.value_counts()

grade
B    606807
C    557667
A    417670
D    258964
E     97552
F     26610
G      7317
Name: count, dtype: int64

In [132]:
# 불량 우량 합치기
two_answer_df = pd.DataFrame({'불량': badDf2.grade.value_counts(), '우량': goodDf2.grade.value_counts()})
two_answer_df

          불량      우량
grade
A      15357  417670
B      56750  606807
C      92386  557667
D      65460  258964
E      38087   97552
F      15190   26610
G       4851    7317

## 문제3) 대출 총액과 대출 이자율 간의 상관관계 파악 (상관관계 파악하는 함수 쓰면 될듯)

In [135]:
## 대출 금액과 대출 이자율 상관관계 파악 
three_answer = df2.loan_amnt.corr(df2.int_rate)
three_answer

np.float64(0.09808333533023428)

## 각 결과를 csv 파일로 저장하기.

In [131]:
## 1번 문제 저장
one_answer_df

loan_amnt    34016115925
dtype: int64

In [ ]:
one_answer_df.to_csv('./result/3-05)one_answer.csv', index=False)

In [133]:
## 2번 문제 저장
two_answer_df

          불량      우량
grade
A      15357  417670
B      56750  606807
C      92386  557667
D      65460  258964
E      38087   97552
F      15190   26610
G       4851    7317

In [ ]:
# 저장하기
two_answer_df.to_csv('./result/3-05)two_answer.csv', encoding='utf-8-sig') # utf-8-sig: 한글 깨짐 방지

In [136]:
## 3번 문제 저장
three_answer

np.float64(0.09808333533023428)

In [ ]:
# 저장하기
np.savetxt('./result/3-05)three_answer.csv', [three_answer], fmt='%.5f', delimiter=',')

In [185]:
# 문제3-교수님풀이) 
df2.head()

   loan_amnt loan_status grade  int_rate       term  bad_loan_status
0       2500     Current     C     13.56  36 months            False
1      30000     Current     D     18.94  36 months            False
2       5000     Current     D     17.97  36 months            False
3       4000     Current     D     18.94  36 months            False
4      30000     Current     C     16.14  36 months            False

In [187]:
df2.loan_amnt.corr(df2.int_rate) # 상관관계 크지않다.

np.float64(0.09808333533023428)

In [188]:
bad_loan_status_to_grades

grade
B    383075
C    374606
A    227188
D    198279
E     92861
F     31922
G      9157
Name: count, dtype: int64

In [ ]:
bad_loan_status_to_grades.sort_index().to_csv('./result/3-05)bad_loan_status_교수님.csv', sep=',')